In [106]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sqlalchemy import create_engine
import warnings
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [107]:
postgres_user = 'dsbc_student'
postgres_pw = '7*.8G9QH21'
postgres_host = '142.93.121.174'
postgres_port = '5432'
postgres_db = 'useducation'

warnings.filterwarnings('ignore')
sns.set(style="whitegrid")

engine = create_engine('postgresql://{}:{}@{}:{}/{}'.format(
    postgres_user, postgres_pw, postgres_host, postgres_port, postgres_db))

df = pd.read_sql_query('select * from useducation',con=engine)

# no need for an open connection, 
# as we're only doing a single query
engine.dispose()

In [108]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1492 entries, 0 to 1491
Data columns (total 25 columns):
PRIMARY_KEY                     1492 non-null object
STATE                           1492 non-null object
YEAR                            1492 non-null int64
ENROLL                          1229 non-null float64
TOTAL_REVENUE                   1280 non-null float64
FEDERAL_REVENUE                 1280 non-null float64
STATE_REVENUE                   1280 non-null float64
LOCAL_REVENUE                   1280 non-null float64
TOTAL_EXPENDITURE               1280 non-null float64
INSTRUCTION_EXPENDITURE         1280 non-null float64
SUPPORT_SERVICES_EXPENDITURE    1280 non-null float64
OTHER_EXPENDITURE               1229 non-null float64
CAPITAL_OUTLAY_EXPENDITURE      1280 non-null float64
GRADES_PK_G                     1319 non-null float64
GRADES_KG_G                     1360 non-null float64
GRADES_4_G                      1361 non-null float64
GRADES_8_G                      1

In [109]:
df.head()

PRIMARY_KEY       STATE  YEAR  ENROLL  TOTAL_REVENUE  FEDERAL_REVENUE  \
0     1992_ALABAMA     ALABAMA  1992     NaN      2678885.0         304177.0   
1      1992_ALASKA      ALASKA  1992     NaN      1049591.0         106780.0   
2     1992_ARIZONA     ARIZONA  1992     NaN      3258079.0         297888.0   
3    1992_ARKANSAS    ARKANSAS  1992     NaN      1711959.0         178571.0   
4  1992_CALIFORNIA  CALIFORNIA  1992     NaN     26260025.0        2072470.0   

   STATE_REVENUE  LOCAL_REVENUE  TOTAL_EXPENDITURE  INSTRUCTION_EXPENDITURE  \
0      1659028.0       715680.0          2653798.0                1481703.0   
1       720711.0       222100.0           972488.0                 498362.0   
2      1369815.0      1590376.0          3401580.0                1435908.0   
3       958785.0       574603.0          1743022.0                 964323.0   
4     16546514.0      7641041.0         27138832.0               14358922.0   

   ...  GRADES_4_G  GRADES_8_G  GRADES_12_G  GRADES_1_8_G  GRADES_9_12_G  \
0  ...     57948.0     58025.0      41167.0      471564.0       196386.0   
1  ...      9748.0      8789.0       6714.0       79117.0        30847.0   
2  ...     55433.0     49081.0      37410.0      437127.0       175210.0   
3  ...     34632.0     36011.0      27651.0      281338.0       123113.0   
4  ...    418418.0    363296.0     270675.0     3286034.0      1372011.0   

   GRADES_ALL_G  AVG_MATH_4_SCORE  AVG_MATH_8_SCORE  AVG_READING_4_SCORE  \
0      676174.0        208.327876        252.187522           207.963517   
1      112335.0               NaN               NaN                  NaN   
2      614881.0        215.253932        265.366278           206.212716   
3      405259.0        210.206028        256.312090           208.634458   
4     4717112.0        208.398961        260.892247           196.764414   

   AVG_READING_8_SCORE  
0                  NaN  
1           258.859712  
2           262.169895  
3           264.619665  
4                  NaN  

[5 rows x 25 columns]

In [110]:
df.isnull().sum()*100/df.isnull().count()

PRIMARY_KEY                      0.000000
STATE                            0.000000
YEAR                             0.000000
ENROLL                          17.627346
TOTAL_REVENUE                   14.209115
FEDERAL_REVENUE                 14.209115
STATE_REVENUE                   14.209115
LOCAL_REVENUE                   14.209115
TOTAL_EXPENDITURE               14.209115
INSTRUCTION_EXPENDITURE         14.209115
SUPPORT_SERVICES_EXPENDITURE    14.209115
OTHER_EXPENDITURE               17.627346
CAPITAL_OUTLAY_EXPENDITURE      14.209115
GRADES_PK_G                     11.595174
GRADES_KG_G                      8.847185
GRADES_4_G                       8.780161
GRADES_8_G                       8.780161
GRADES_12_G                      8.780161
GRADES_1_8_G                     8.780161
GRADES_9_12_G                    8.780161
GRADES_ALL_G                    11.595174
AVG_MATH_4_SCORE                64.075067
AVG_MATH_8_SCORE                64.343164
AVG_READING_4_SCORE             64

In [111]:
for column_name in df.columns:
    print("Unique values in column {} are: {}".format(column_name, df[column_name].nunique()))

Unique values in column PRIMARY_KEY are: 1487
Unique values in column STATE are: 80
Unique values in column YEAR are: 26
Unique values in column ENROLL are: 1224
Unique values in column TOTAL_REVENUE are: 1274
Unique values in column FEDERAL_REVENUE are: 1275
Unique values in column STATE_REVENUE are: 1251
Unique values in column LOCAL_REVENUE are: 1275
Unique values in column TOTAL_EXPENDITURE are: 1275
Unique values in column INSTRUCTION_EXPENDITURE are: 1275
Unique values in column SUPPORT_SERVICES_EXPENDITURE are: 1275
Unique values in column OTHER_EXPENDITURE are: 1222
Unique values in column CAPITAL_OUTLAY_EXPENDITURE are: 1275
Unique values in column GRADES_PK_G are: 1261
Unique values in column GRADES_KG_G are: 1348
Unique values in column GRADES_4_G are: 1340
Unique values in column GRADES_8_G are: 1347
Unique values in column GRADES_12_G are: 1342
Unique values in column GRADES_1_8_G are: 1360
Unique values in column GRADES_9_12_G are: 1358
Unique values in column GRADES_ALL_

In [112]:
df = df.interpolate()
df = df.interpolate(method ='linear', limit_direction ='backward')

In [113]:
df.isnull().sum()*100/df.isnull().count()

PRIMARY_KEY                     0.0
STATE                           0.0
YEAR                            0.0
ENROLL                          0.0
TOTAL_REVENUE                   0.0
FEDERAL_REVENUE                 0.0
STATE_REVENUE                   0.0
LOCAL_REVENUE                   0.0
TOTAL_EXPENDITURE               0.0
INSTRUCTION_EXPENDITURE         0.0
SUPPORT_SERVICES_EXPENDITURE    0.0
OTHER_EXPENDITURE               0.0
CAPITAL_OUTLAY_EXPENDITURE      0.0
GRADES_PK_G                     0.0
GRADES_KG_G                     0.0
GRADES_4_G                      0.0
GRADES_8_G                      0.0
GRADES_12_G                     0.0
GRADES_1_8_G                    0.0
GRADES_9_12_G                   0.0
GRADES_ALL_G                    0.0
AVG_MATH_4_SCORE                0.0
AVG_MATH_8_SCORE                0.0
AVG_READING_4_SCORE             0.0
AVG_READING_8_SCORE             0.0
dtype: float64

In [114]:
df["overall_score"] = (df["GRADES_4_G"]*
                                 ((df["AVG_MATH_4_SCORE"] + df["AVG_READING_4_SCORE"])*0.5) +
                                 df["GRADES_8_G"]*((df["AVG_MATH_8_SCORE"] +
                                 df["AVG_READING_8_SCORE"])*0.5))/(df["GRADES_4_G"] + df["GRADES_8_G"])

In [115]:
vals = df[['overall_score', 'TOTAL_EXPENDITURE', 'INSTRUCTION_EXPENDITURE',
                                      'SUPPORT_SERVICES_EXPENDITURE', 'OTHER_EXPENDITURE', 
                                      'CAPITAL_OUTLAY_EXPENDITURE']]

In [116]:
#INSTRUCTION_EXPENDITURE has the highest correlation to the overall score
vals.corr()

overall_score  TOTAL_EXPENDITURE  \
overall_score                      1.000000           0.211001   
TOTAL_EXPENDITURE                  0.211001           1.000000   
INSTRUCTION_EXPENDITURE            0.213368           0.992757   
SUPPORT_SERVICES_EXPENDITURE       0.228103           0.992496   
OTHER_EXPENDITURE                  0.190825           0.948062   
CAPITAL_OUTLAY_EXPENDITURE         0.137434           0.928443   

                              INSTRUCTION_EXPENDITURE  \
overall_score                                0.213368   
TOTAL_EXPENDITURE                            0.992757   
INSTRUCTION_EXPENDITURE                      1.000000   
SUPPORT_SERVICES_EXPENDITURE                 0.979327   
OTHER_EXPENDITURE                            0.916810   
CAPITAL_OUTLAY_EXPENDITURE                   0.896026   

                              SUPPORT_SERVICES_EXPENDITURE  OTHER_EXPENDITURE  \
overall_score                                     0.228103           0.190825   
TOTAL_EXPENDITURE                                 0.992496           0.948062   
INSTRUCTION_EXPENDITURE                           0.979327           0.916810   
SUPPORT_SERVICES_EXPENDITURE                      1.000000           0.949715   
OTHER_EXPENDITURE                                 0.949715           1.000000   
CAPITAL_OUTLAY_EXPENDITURE                        0.905785           0.920934   

                              CAPITAL_OUTLAY_EXPENDITURE  
overall_score                                   0.137434  
TOTAL_EXPENDITURE                               0.928443  
INSTRUCTION_EXPENDITURE                         0.896026  
SUPPORT_SERVICES_EXPENDITURE                    0.905785  
OTHER_EXPENDITURE                               0.920934  
CAPITAL_OUTLAY_EXPENDITURE                      1.000000

In [124]:
# Normalize the data so that all variables have a mean of 0 and standard deviation
# of 1.
exp = df[['INSTRUCTION_EXPENDITURE', 'SUPPORT_SERVICES_EXPENDITURE', 'OTHER_EXPENDITURE', 'CAPITAL_OUTLAY_EXPENDITURE']]

X = StandardScaler().fit_transform(exp)

# The NumPy covariance function assumes that variables are represented by rows,
# not columns, so we transpose X.
Xt = X.T
Cx = np.cov(Xt)
print('Covariance Matrix:\n', Cx)

Covariance Matrix:
 [[1.00067069 0.97998361 0.91742485 0.89662726]
 [0.97998361 1.00067069 0.95035186 0.9063927 ]
 [0.91742485 0.95035186 1.00067069 0.92155211]
 [0.89662726 0.9063927  0.92155211 1.00067069]]


In [132]:
sklearn_pca = PCA(n_components=1)
df["pca_1"] = sklearn_pca.fit_transform(X)

P = eig_vec_cov[:, 0]

# Transform X into Y.
Y = P.T.dot(Xt)

print(
    'The percentage of total variance in the dataset explained by each',
    'component from Sklearn PCA.\n',
    sklearn_pca.explained_variance_ratio_
)

The percentage of total variance in the dataset explained by each component from Sklearn PCA.
 [0.94618368]


In [133]:
df[["overall_score", "pca_1", "TOTAL_EXPENDITURE", "INSTRUCTION_EXPENDITURE",
              "SUPPORT_SERVICES_EXPENDITURE", "OTHER_EXPENDITURE", "CAPITAL_OUTLAY_EXPENDITURE"]].corr()

overall_score     pca_1  TOTAL_EXPENDITURE  \
overall_score                      1.000000  0.198192           0.211001   
pca_1                              0.198192  1.000000           0.992724   
TOTAL_EXPENDITURE                  0.211001  0.992724           1.000000   
INSTRUCTION_EXPENDITURE            0.213368  0.974930           0.992757   
SUPPORT_SERVICES_EXPENDITURE       0.228103  0.985919           0.992496   
OTHER_EXPENDITURE                  0.190825  0.973478           0.948062   
CAPITAL_OUTLAY_EXPENDITURE         0.137434  0.956322           0.928443   

                              INSTRUCTION_EXPENDITURE  \
overall_score                                0.213368   
pca_1                                        0.974930   
TOTAL_EXPENDITURE                            0.992757   
INSTRUCTION_EXPENDITURE                      1.000000   
SUPPORT_SERVICES_EXPENDITURE                 0.979327   
OTHER_EXPENDITURE                            0.916810   
CAPITAL_OUTLAY_EXPENDITURE                   0.896026   

                              SUPPORT_SERVICES_EXPENDITURE  OTHER_EXPENDITURE  \
overall_score                                     0.228103           0.190825   
pca_1                                             0.985919           0.973478   
TOTAL_EXPENDITURE                                 0.992496           0.948062   
INSTRUCTION_EXPENDITURE                           0.979327           0.916810   
SUPPORT_SERVICES_EXPENDITURE                      1.000000           0.949715   
OTHER_EXPENDITURE                                 0.949715           1.000000   
CAPITAL_OUTLAY_EXPENDITURE                        0.905785           0.920934   

                              CAPITAL_OUTLAY_EXPENDITURE  
overall_score                                   0.137434  
pca_1                                           0.956322  
TOTAL_EXPENDITURE                               0.928443  
INSTRUCTION_EXPENDITURE                         0.896026  
SUPPORT_SERVICES_EXPENDITURE                    0.905785  
OTHER_EXPENDITURE                               0.920934  
CAPITAL_OUTLAY_EXPENDITURE                      1.000000